# Generated by Django 6.0.3 on 2026-03-10 17:24

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DisasterEventsPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True,
                        default="Explore multi-decade EM-DAT events, view affected regions, and read event storylines.",
                        max_length=255,
                    ),
                ),
                (
                    "default_hazard",
                    models.CharField(
                        choices=[("drought", "Drought"), ("flood", "Flood")],
                        default="drought",
                        help_text="Default hazard type shown on page load.",
                        max_length=20,
                    ),
                ),
                (
                    "calendar_start_year",
                    models.IntegerField(
                        default=2020,
                        help_text="First year displayed in the calendar heatmap.",
                    ),
                ),
                (
                    "calendar_end_year",
                    models.IntegerField(
                        default=2025,
                        help_text="Last year displayed in the calendar heatmap.",
                    ),
                ),
                (
                    "topojson_url",
                    models.URLField(
                        blank=True,
                        default="/static/data/ea_adm2.topojson",
                        help_text="URL to the Admin boundary TopoJSON file.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Disaster Events Page",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="IBFForecastPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True,
                        default="Admin1 Bayesian Network seasonal probability and severity projections.",
                        max_length=255,
                    ),
                ),
                (
                    "body",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="Introductory content for the IBF forecast section.",
                    ),
                ),
                (
                    "ibf_dashboard_url",
                    models.URLField(
                        blank=True, help_text="External URL to the full IBF dashboard."
                    ),
                ),
                (
                    "default_hazard",
                    models.CharField(
                        choices=[("drought", "Drought"), ("flood", "Flood")],
                        default="drought",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "IBF Forecast Page",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="RiskMonitoringPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True,
                        default="Regional situational awareness for flood and drought monitoring.",
                        max_length=255,
                    ),
                ),
                (
                    "body",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="Introductory content for the risk monitoring section.",
                    ),
                ),
                (
                    "crma_dashboard_url",
                    models.URLField(
                        blank=True, help_text="External URL to the full CRMA dashboard."
                    ),
                ),
                (
                    "default_hazard",
                    models.CharField(
                        choices=[("drought", "Drought"), ("flood", "Flood")],
                        default="drought",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Risk Monitoring Page",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="StorylineEntry",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "hazard_type",
                    models.CharField(
                        choices=[("drought", "Drought"), ("flood", "Flood")],
                        max_length=20,
                    ),
                ),
                (
                    "event_key",
                    models.CharField(
                        blank=True,
                        help_text="EM-DAT event key (e.g. drought-2023-03).",
                        max_length=100,
                    ),
                ),
                (
                    "event_date",
                    models.DateField(
                        blank=True, help_text="Date of the disaster event.", null=True
                    ),
                ),
                (
                    "body",
                    wagtail.fields.RichTextField(
                        help_text="Narrative storyline for this event."
                    ),
                ),
                (
                    "regions_affected",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated list of affected regions.",
                        max_length=500,
                    ),
                ),
            ],
            options={
                "verbose_name": "Storyline Entry",
                "verbose_name_plural": "Storyline Entries",
            },
            bases=("wagtailcore.page",),
        ),
    ]
