# Generated by Django 6.0.3 on 2026-03-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disastereventspage",
            name="topojson_url",
            field=models.CharField(
                blank=True,
                default="/static/data/ea_adm2.topojson",
                help_text="Path or URL to the Admin boundary TopoJSON file.",
                max_length=500,
            ),
        ),
    ]
