# Generated by Django 6.0.3 on 2026-03-10 17:24

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_create_homepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="banner_subtitle",
            field=models.CharField(
                blank=True,
                default="Flood & Drought Early Warning for East Africa",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="banner_title",
            field=models.CharField(
                default="E4DRR Early Warning System", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="intro_text",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="Explore multi-decade EM-DAT disaster events, risk monitoring dashboards, and impact-based forecasts.",
            ),
        ),
    ]
